kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: vsphere-ssd-sc
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

  grafana:
    adminPassword: admin
    enabled: true
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboardsConfigMaps:
      default: ethereum-grafana-dashboards
    persistence:
      enabled: true
      type: sts
      storageClassName: vsphere-ssd-sc
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection
