name: Deploy Prometheus Stack for K8s
run-name:  Deploy Prometheus Stack for K8s ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    env:
      CHART_PATH: charts/prometheus
      DEPLOYMENT_NAME: vc-k8s-prometheus-stack
      NAMESPACE: prometheus
      VALUES: values.yaml

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Connect to Twingate
      uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_SERVICE_KEY }}

    - name: Set up KUBECONFIG
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Install Helm Dependencies
      run: |
        helm dependency update ${{ env.CHART_PATH }}

    - name: Print Helm Diff
      run: |
        helm diff --context=3 upgrade --color --allow-unreleased --namespace ${{ env.NAMESPACE }} ${{ env.DEPLOYMENT_NAME }} ${{ env.CHART_PATH }} -f ${{ env.CHART_PATH }}/${{ env.VALUES }}

    - name: Helm Deploy
      run: |
        helm upgrade --install --wait --timeout 5m  --namespace ${{ env.NAMESPACE }} ${{ env.DEPLOYMENT_NAME }} ${{ env.CHART_PATH }} -f ${{ env.CHART_PATH }}/${{ env.VALUES }}
